name: Zip FluentUI Web Components

on:
  workflow_dispatch:  # 手动触发

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout only web-components
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            packages/web-components
          fetch-depth: 1

      - name: Compress to ZIP
        run: |
          mkdir output
          zip -r output/fluentui-web-components.zip packages/web-components

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: fluentui-web-components
          path: output/fluentui-web-components.zip
